import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Profile from '../components/Profile'
import styles from '../styles/Home.module.css'
import React, { useState, useEffect } from "react";
import { isAuthenticated } from '../services/noauth';

export default function Home() {
  const [logged, setLogged] = useState(false);
  useEffect(() => {
    setLogged(isAuthenticated());
  }, [isAuthenticated()]);
  console.log('index user', logged)
  return (
    <div className={styles.container}>
      <Head>
        <title>Lineup Utility</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          FestiGram Lineup Utility
        </h1>

        <p className={styles.description}>
          Login to enter a festival lineup
        </p>

        {logged && <Link href="/lineup">Assign a lineup</Link>}

        {!logged && <a href="/auth/login" className={styles.card}>Login</a>}

        {logged && <a href="/auth/logout" className={styles.card}>Logout</a>}

        <Profile />

      </main>

      <footer className={styles.footer}>
        <a
          href="https://festigram.app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by FestiGram
        </a>
      </footer>
    </div>
  )
}
