import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Profile from '../components/Profile'
import styles from '../styles/Home.module.css'
import React, { useState, useEffect } from "react";
import { useUser } from '@auth0/nextjs-auth0';

export default function Home() {
	const { user } = useUser()
	//console.log('index user', user)
  return (
    <div className={styles.container}>
      <Head>
        <title>FestiGram Lineup Utility</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          FestiGram Lineup Utility
        </h1>

        <p className={styles.description}>
          Login to enter a festival lineup
        </p>

        {user && <Link href="/lineup">Assign a lineup</Link>}

        {!user && <a href="/api/auth/login" className={styles.card}>Login</a>}

        {user && <a href="/api/auth/logout" className={styles.card}>Logout</a>}

        <Profile />

      </main>

      <footer className={styles.footer}>
        <a
          href="https://festigram.app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by FestiGram
        </a>
      </footer>
    </div>
  )
}
